<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container12Hdas9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container12Hdas9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container12Hdas9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container12Hdas9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container12Hdas9\srcDevDebugProjectContainer(array(
    'container.build_hash' => '12Hdas9',
    'container.build_id' => '4b0b48c1',
    'container.build_time' => 1540915326,
), __DIR__.\DIRECTORY_SEPARATOR.'Container12Hdas9');
